InStockWebAppPL/Controllers/FilterProductController.cs
using AutoMapper;
using InStockWebAppBLL.Features.Interfaces.Domain;
using InStockWebAppBLL.Models.CategoryVM;
using InStockWebAppBLL.Models.SubCategoryVM;
using InStockWebAppDAL.Context;
using InStockWebAppDAL.Entities;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Security.Claims;
using InStockWebAppBLL.Features.Interfaces;
using Microsoft.AspNetCore.OutputCaching;

namespace InStockWebAppPL.Controllers
{
    public class FilterProductController : Controller
    {
        private readonly ICategoryRepository categoryRepository;
        private readonly IMapper mapper;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IFilterRepository filter;
        private readonly ISubCategoryRepository subCategoryRepository;

        public FilterProductController(IFilterRepository filter,
            ISubCategoryRepository subCategoryRepository, ICategoryRepository categoryRepository,
            IMapper mapper, IUnitOfWork unitOfWork)
        {
            this.categoryRepository = categoryRepository;
            this.mapper = mapper;
            _unitOfWork = unitOfWork;
            this.filter = filter;
            this.subCategoryRepository = subCategoryRepository;
        }

        [ResponseCache(Duration = 0, NoStore = true, Location = ResponseCacheLocation.Client)]

        public async Task<IActionResult> Index(int ? id = null)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier);
            if (claim is not null)
            {
                var userId = claim.Value;
                var count = await _unitOfWork.CartRepository.GetCartItemsCount(userId);
                HttpContext.Session.SetInt32("shoppingCartSession", count);
            }

            var pageSize = 6;


            ViewBag.Catogery = mapper
                .Map<IEnumerable<GetAllCategoriesVM>>
                    (await categoryRepository.GetAll());

            ViewBag.SubCategory = mapper
                .Map<IEnumerable<SubcategoryVM>>
                    (await subCategoryRepository.GetAll());



            ViewBag.TotalPages = await filter.totalCount();

            ViewBag.CurrentPage = (int)Math.Ceiling(await filter.totalCount() / (double)pageSize);
            TempData["CategoeyID"]=id;
            var products = await filter.GetProductsForPage(1, pageSize);
            var totalcount = await filter.totalCount();
            ViewBag.TotalPages = totalcount;

            ViewBag.CurrentPage = 1;

            ViewBag.ProductCount = totalcount;
            var result = products.Where(a => a.SubCategory.CategoryId ==id).ToList();
            return View(result);
        }
        [ResponseCache(Duration = 0, NoStore = true, Location = ResponseCacheLocation.Client)]


        [HttpGet]
        public async Task<IActionResult> Get(int page = 1, int pageSize = 6, string sortOption = "default", int? categoryId = null, string subcategoryIds = null, int minPrice = 0, int maxPrice = 1000000, string search = null)
        {
            int? categoryid = (int?)TempData["CategoeyID"];
            if(categoryid !=null)
            {
                categoryId = categoryid;

            }
            var productList = await filter.GetByFilter(page, pageSize, sortOption, categoryId, subcategoryIds, minPrice, maxPrice, search);

            var totalProducts = await filter.totalCount();
            var totalPages = (int)Math.Ceiling(totalProducts / (double)pageSize);

            return PartialView("_ProductList", productList);
        }

        public IActionResult Sort(string sortOption)
        {
            return RedirectToAction("Get", new { sortOption = sortOption });
        }

        public async Task<IActionResult> GetSubcategories(int categoryId)
        {
            var subCategory = mapper.Map<IEnumerable<SubcategoryVM>>(
                await subCategoryRepository.getAllSubCategoriesByCategoryId(categoryId));
            return PartialView("_SubCategoryFilter", subCategory);
        }
    }
} 

InStockWebAppPL/Controllers/ProductController.cs
using InStockWebAppBLL.Features.Interfaces.Domain;

using InStockWebAppBLL.Models.HomeVM;
using InStockWebAppBLL.Models.ProductVM;
using InStockWebAppPL.Resources;
using InStockWebAppDAL.Entities;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using InStockWebAppBLL.Helpers.Role;

namespace InStockWebAppPL.Controllers
{
    [Authorize(Roles = @$"{AppRoles.Admin}")]

    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ISubCategoryRepository _subCategoryRepository;
        private readonly IDiscountRepository _discountRepository;
        private readonly IProductImageRepository _imageRepository;
        




        public ProductController(IProductRepository productRepository,
            ISubCategoryRepository subCategoryRepository,IProductImageRepository imageRepository,
            IDiscountRepository discountRepository)
        {
            _productRepository = productRepository;
            _subCategoryRepository = subCategoryRepository;
            _imageRepository=imageRepository;
            _discountRepository = discountRepository;

        }
        [Authorize(Roles = @$"{AppRoles.Admin}")]

        // GET: ProductController
        public async Task<IActionResult> Index()
        {
            return View(await _productRepository.GetAll());
        }
        [Authorize(Roles = @$"{AppRoles.Admin}")]

        // GET: ProductController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            return View(await _productRepository.Details(id));
        }


        [AllowAnonymous]

        public async Task<IActionResult> ProductDetailes(int? id)
        {
            var details = await _productRepository.Details(id);

            return PartialView("_ProductDetailes", details);
        }


        [AllowAnonymous]
        // GET: ProductController/Details/5
        public async Task<IActionResult> CustomerSideDetails(int id)
        {
            ViewBag.ID = id;
            var details = await _productRepository.Details(id);

            var product = await _productRepository.GetProductWithSubcategoryById(id);

            var categoryWithProductsVM = new CategoryWithProductsVM
            {
                Id = product.SubCategory.CategoryId,
                Name = product.SubCategory.Name,
                Description = product.SubCategory.Description,
                CreatedAt = product.SubCategory.CreatedAt,
                ModifiedAt = product.SubCategory.ModifiedAt,
                DeletedAt = product.SubCategory.DeletedAt,
                IsDeleted = product.SubCategory.IsDeleted,
                SubCategories = await _subCategoryRepository.getAllSubCategoriesByCategoryId(product.SubCategory.CategoryId)
            };

            if (categoryWithProductsVM.SubCategories != null)
            {
                foreach (var subcategory in categoryWithProductsVM.SubCategories)
                {
                    if (subcategory.IsDeleted == true) { continue; }

                    subcategory.Products = await _productRepository.GetProductsBySubcategoryId(subcategory.Id);

                    if (subcategory.Products != null)
                    {
                        categoryWithProductsVM.Products ??= new List<Product>();
                        categoryWithProductsVM.Products.AddRange(subcategory.Products);
                    }
                }
            }

            if (categoryWithProductsVM.Products != null)
            {
                categoryWithProductsVM.Products = categoryWithProductsVM.Products.Where(p => p.Id != id).ToList();
            }

            if (categoryWithProductsVM.Products != null)
            {
                var rnd = new Random();
                categoryWithProductsVM.Products = categoryWithProductsVM.Products.OrderBy(p => rnd.Next()).ToList();
            }

            ViewBag.RelatedProducts = categoryWithProductsVM.Products;

            return View(details);
        }
        [Authorize(Roles = @$"{AppRoles.Admin}")]

        [HttpGet]
        // GET: ProductController/Create
        public async Task<IActionResult> Create()
        {
            ViewData["SubCategoryId"] = new SelectList(await _subCategoryRepository.GetAll(), "Id", "Name");
            var emptyOption = new SelectListItem() { Value = "", Text = "No Discount" };
            var selectList = new SelectList(await _discountRepository.GetAll(), "Id", "Name");
            var finalList = new List<SelectListItem> { emptyOption };
            finalList.AddRange(selectList);
            ViewData["DiscountId"] = finalList;
            return View();
        }
        [Authorize(Roles = @$"{AppRoles.Admin}")]

        // POST: ProductController/Create
        [HttpPost]
        public async Task<IActionResult> Create(AlterProductVM entityVM, List<IFormFile>? ImageFiles)
        {
            try
            {
                ModelState["ImageFiles"].ValidationState = ModelValidationState.Valid;
                if (ModelState.IsValid)
                {
                   
                    int createdId=await _productRepository.Add(entityVM);
                    if (createdId != -1)
                    {
                        await _imageRepository.add(ImageFiles,createdId);
                        return RedirectToAction(nameof(Index));
                    }
                }
                ViewData["SubCategoryId"] = new SelectList(await _subCategoryRepository.GetAll(), "Id", "Name");
                var emptyOption = new SelectListItem() { Value = "", Text = "No Discount" };
                var selectList = new SelectList(await _discountRepository.GetAll(), "Id", "Name");
                var finalList = new List<SelectListItem> { emptyOption };
                finalList.AddRange(selectList);
                ViewData["DiscountId"] = finalList;
                return View(entityVM);
            }
            catch
            {
                return View();
            }
        }
        [Authorize(Roles = @$"{AppRoles.Admin}")]

        // GET: ProductController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {   if (id == null) return NotFound();
            var product = await _productRepository.EditDetails(id);
            if(product==null)return NotFound();
            ViewData["SubCategoryId"] = new SelectList(await _subCategoryRepository.GetAll(), "Id", "Name");
            var emptyOption = new SelectListItem() { Value = "", Text = "No Discount" };
            var selectList = new SelectList(await _discountRepository.GetAll(), "Id", "Name");
            var finalList = new List<SelectListItem> { emptyOption };
            finalList.AddRange(selectList);
            ViewData["DiscountId"] = finalList;
            return View(product);
        }
        [Authorize(Roles = @$"{AppRoles.Admin}")]

        // POST: ProductController/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, AlterProductVM entityVM,List<IFormFile>? ImageFiles)
        {
            try
            {
                ModelState["ImageFiles"].ValidationState= ModelValidationState.Valid;
                if (ModelState.IsValid) { 
                    var oldProduct=await _productRepository.GetById(id);
                    await _productRepository.Update(id,entityVM);
                    //Delete Images if no other product is referring to it.
                    await _imageRepository.remove(oldProduct.Images, id);
                    await _imageRepository.add(ImageFiles, id);
                    return RedirectToAction(nameof(Index));
                }
                ViewData["SubCategoryId"] = new SelectList(await _subCategoryRepository.GetAll(), "Id", "Name");
                var emptyOption = new SelectListItem() { Value = "", Text = "No Discount" };
                var selectList = new SelectList(await _discountRepository.GetAll(), "Id", "Name");
                var finalList = new List<SelectListItem>{ emptyOption};
                finalList.AddRange(selectList);
                ViewData["DiscountId"] = finalList;
                return View(entityVM);
            }
            catch
            {
                return View();
            }
        }
        [Authorize(Roles = @$"{AppRoles.Admin}")]

        //Post: ProductController/ToggleStatus/5
        [HttpPost]
        public async Task<IActionResult> ToggleStatus(int id)
        {
            var toggleDateTime = await _productRepository.ToggleStatus(id);
            if (toggleDateTime !=null)
                return Ok(toggleDateTime);
            return NotFound();
        }
    }
}

InStockWebAppPL/Views/Cart/Index.cshtml
@model CartVM
@{
    ViewBag.Title = "InStock | Shopping Cart";
    Layout = "~/Views/Shared/Customer/_Layout.cshtml";

    List<Item> items = [];
    if (Model != null)
    {
        items = Model.Items.ToList();
    }
}

@section CSS {
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
}

<div class="container">
    <!-- HERO SECTION-->
    <section class="py-5 bg-light">
        <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                <div class="col-lg-6">
                    <h1 class="h2 text-uppercase mb-0">Cart</h1>
                </div>
                <div class="col-lg-6 text-lg-end">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-lg-end mb-0 px-0 bg-light">
                            <li class="breadcrumb-item">
                                <a class="text-dark" asp-controller="Home" asp-action="">Home</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Cart</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <section class="py-5">
        <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>
        <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
                <!-- CART TABLE-->
                <div class="table-responsive mb-4">
                    <table class="table text-nowrap">
                        <thead class="bg-light">
                        <tr>
                            <th class="border-0 p-3" scope="col">
                                <strong class="text-sm text-uppercase">Product</strong>
                            </th>
                            <th class="border-0 p-3" scope="col">
                                <strong class="text-sm text-uppercase">Price</strong>
                            </th>
                            <th class="border-0 p-3" scope="col">
                                <strong class="text-sm text-uppercase">Quantity</strong>
                            </th>
                            <th class="border-0 p-3" scope="col">
                                <strong class="text-sm text-uppercase">Total</strong>
                            </th>
                            <th class="border-0 p-3" scope="col">
                                <strong class="text-sm text-uppercase"></strong>
                            </th>
                        </tr>
                        </thead>
                        <tbody class="border-0">
                        @for (var i = 0; i < items?.Count; i++)
                        {
                            @* @items[i].Product.Images[0].ImagePath *@
                            <tr id="#row-@items[i].Id">
                                <td class="ps-0 py-3 border-light" scope="row">
                                    <div class="d-flex align-items-center ">
                                            <a class="reset-anchor d-block animsition-link" asp-action="CustomerSideDetails" asp-controller="Product" asp-route-id="@items[i]?.Product?.Id">
                                                <img src="~/Files/ProductImages/@items[i]?.Product?.Images?.FirstOrDefault()?.ImagePath" alt="..." width="70" />
                                        </a>
                                        <div class="ms-3">
                                            <strong style="width:30px" class="h6">
                                                    <a class="reset-anchor animsition-link" asp-action="CustomerSideDetails" asp-controller="Product" asp-route-id="@items[i]?.Product?.Id">@items[i].Product.Name</a>
                                            </strong>
                                        </div>
                                    </div>
                                </td>
                                <td class="p-3 align-middle border-light">
                                    <p class="mb-0 small">$@items[i].Product.Price</p>
                                </td>
                                <td class="p-3 align-middle border-light">
                                    <div class="border d-flex align-items-center justify-content-between px-3">
                                        <span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                                        <div class="quantity">
                                            <button class="decreaseButton dec-btn p-0" data-item-id="@items[i].Id">
                                                <i class="fas fa-caret-left"></i>
                                            </button>
                                            <input class="form-control form-control-sm border-0 shadow-0 p-0 quantityInput" type="text" asp-for="Items.ToList()[i].Quantity"/>
                                            @if (items[i].Product.InStock > items[i].Quantity)
                                            {
                                                <button class="increaseButton inc-btn p-0" data-item-id="@items[i].Id" data-index="@i">
                                                    <i class="fas fa-caret-right"></i>
                                                </button>
                                            }
                                            else
                                            {
                                                <button type="button" class="inc-btn p-0" disabled>
                                                    <i class="fas fa-caret-right"></i>
                                                </button>
                                            }
                                        </div>
                                    </div>
                                </td>
                                <td class="p-3 align-middle border-light">
                                    <p class="mb-0 small totalPrice">@items[i].TotalPrice EGP</p>
                                </td>
                                <td class="p-3 align-middle border-light">
                                    <button type="button" data-item-id="@items[i].Id" class="reset-anchor deleteCartItem" style="border: none; background-color: #fff;">
                                        <i class="fas fa-trash-alt small text-muted"></i>
                                    </button>

                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
                <!-- CART NAV-->
                <div class="bg-light px-4 py-3">
                    <div class="row align-items-center text-center">
                        <div class="col-md-6 mb-3 mb-md-0 text-md-start">
                            <a class="btn btn-link p-0 text-dark btn-sm" asp-controller="FilterProduct" asp-action="Index"><i class="fas fa-long-arrow-alt-left me-2"> </i>Continue shopping</a>
                        </div>
                        <div class="col-md-6 text-md-end">


                            @if (Model != null)
                            {
                                if (ViewBag.Cart !=0)
                                {
                                    <a asp-action="Checkout" asp-controller="Home" class="btn btn-outline-dark btn-sm checkout">Proceed to checkout</a>
                                     
                                }
                           
                            }

                        </div>

                    </div>
                </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
                <div class="card border-0 rounded-0 p-lg-4 bg-light">
                    <div class="card-body">
                        <h5 class="text-uppercase mb-4">Cart total</h5>
                        <ul class="list-unstyled mb-0">
                            <li class="d-flex align-items-center justify-content-between">
                                <strong class="text-uppercase small font-weight-bold">Subtotal</strong><span class="text-muted small totalcard">@Model?.TotalPrice  EGP</span>
                            </li>
                            <li class="border-bottom my-2"></li>
                            <li class="d-flex align-items-center justify-content-between mb-4">
                                <strong class="text-uppercase small font-weight-bold">Total</strong><span class="totalcard">@Model?.TotalPrice EGP</span>
                            </li>
                            <li>
                                <form action="#">
                                    <div class="input-group mb-0">
                                        <input class="form-control" type="text" placeholder="Enter your coupon">
                                        <button class="btn btn-dark btn-sm w-100" type="submit"> <i class="fas fa-gift me-2"></i>Apply coupon</button>
                                    </div>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@section Js
{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="~/cart/cartdetailes.js"></script>
    <script>
        $(document).ready(function () {
            // Check if TempData["SucessPayment"] is not null
            var successPayment = @Html.Raw(Json.Serialize(TempData["SucessPayment"]));

            if (successPayment) {
                // Display toast notification for successful payment
                Toastify({
                    text: "Payment successful!",
                    className: "success",
                    style: {
                        background: "linear-gradient(to right, #00b09b, #96c93d)",
                    },
                    preventDuplicates: true
                }).showToast();
            }
        });
    </script>
    
}